clade: ascomycota
key_prot_table_fn: ../../annotations/splicing_factors.tsv

plot_ogs:
    - METTL16
    - SNRNP27
    - SNRPA1

busco:
    default_busco_lineage: ascomycota
    busco_lineages:
      Homo_sapiens: primates
      Caenorhabditis_elegans: nematoda
      Cryptococcus_neoformans: tremellomycetes
      Ustilago_maydis: basidiomycota

funannotate:
    trusted_annotations:
      - Homo_sapiens
      - Caenorhabditis_elegans
      - Crytococcus_neoformans
      - Ustilago_maydis
      - Schizosaccharomyces_pombe
      - Pneumocystis_jirovecii
      - Aspergillus_nidulans
      - Botrytis_cinerea
      - Neurospora_crassa
      - Fusarium_graminearum
      - Yarrowia_lipolytica
      - Candida_albicans
      - Saccharomyces_cerevisiae
    ploidy: # these species are hybrids
      Zygosaccharomyces_parabailii: 2
      Saccharomyces_pastorianus: 2
      Millerozyma_farinosa: 2
    seed_species:
        yarrowia_lipolytica: # Lipomycetaceae, Trigonopsidacea, Dipodascaceae
            - Lipomyces_starkeyi
            - Lipomyces_japonicus
            - Lipomyces_oligophaga
            - Lipomyces_doorenjongii
            - Kockiozyma_suomiensis
            - Trigonopsis_variabilis
            - Trigonopsis_vinaria
            - Botryozyma_nematodophila
            - Tortispora_starmeri
            - Tortispora_caseinolytica
            - Tortispora_ganteri
            - Candida_hispaniensis
            - Yarrowia_bubula
            - Deakozyma_indianensis
            - Wickerhamiella_sorbophila
            - Wickerhamiella_cacticola
            - Wickerhamiella_domercqiae
            - Wickerhamiella_versatilis
            - Starmerella_apicola
            - Starmerella_bombicola
            - Trichomonascus_ciferii
            - Saprochaete_ingens
            - Saprochaete_fungicola
            - Nadsonia_fulvescens
            - Nadsonia_starkeyihenricii
            - Middelhovenomyces_tepae
            - Magnusiomyces_capitatus
            - Magnusiomyces_tetraspermus
            - Dipodascus_albidus
            - Groenewaldozyma_salmanticensis
            - Zygoascus_ofunaensis
            - Zygoascus_meyerae
            - Diddensiella_caesifluorescens
            - Spencermartinsiella_europaea
            - Blastobotrys_muscicola
            - Blastobotrys_mokoenaii
            - Blastobotrys_aristatus
            - Blastobotrys_raffinosifermentans
            - Sugiyamaella_lignohabitans
            - Sugiyamaella_xylanicola
        candida_albicans: # Alloascoideaceae, Sporopachydermia, CUG-Ala, Pichiaceae, CUG-Ser1
            - Alloascoidea_hylecoeti
            - Sporopachydermia_quercuum
            - Sporopachydermia_lactativora
            - Pachysolen_tannophilus
            - Peterozyma_xylosa
            - Nakazawaea_peltata
            - Nakazawaea_holstii
            - Kuraishia_capsulata
            - Kuraishia_ogatae
            - Candida_boidinii
            - Candida_arabinofermentans
            - Ogataea_parapolymorpha
            - Ogataea_polymorpha
            - Ogataea_methylovora
            - Ogataea_trehaloabstinens
            - Ogataea_kodamae
            - Ogataea_minuta
            - Ogataea_henricii
            - Ogataea_zsoltii
            - Ogataea_pilisensis
            - Ogataea_naganishii
            - Ogataea_ramenticola
            - Ambrosiozyma_maleeae
            - Ambrosiozyma_pseudovanderkliftii
            - Ambrosiozyma_philentoma
            - Ambrosiozyma_kashinagicola
            - Dekkera_bruxellensis
            - Brettanomyces_nanus
            - Brettanomyces_naardenensis
            - Kregervanrija_delftensis
            - Kregervanrija_fluxuum
            - Martiniozyma_abietophila
            - Saturnispora_silvae
            - Saturnispora_serradocipensis
            - Saturnispora_zaruensis
            - Saturnispora_mendoncae
            - Saturnispora_dispora
            - Pichia_membranifaciens
            - Candida_californica
            - Pichia_kudriavzevii
            - Pichia_terricola
            - Pichia_norvegensis
            - Pichia_nakasei
            - Pichia_exigua
            - Pichia_manshurica
            - Pichia_occidentalis
            - Candida_inconspicua
            - Komagataella_kurtzmanii
            - Komagataella_phaffii
            - Komagataella_pastoris
            - Citeromyces_siamensis
            - Citeromyces_matritensis
            - Babjeviella_inositovora
            - Cephaloascus_fragrans
            - Cephaloascus_albidus
            - Diutina_rugosa
            - Diutina_catenulata
            - Candida_schatavii
            - Kurtzmaniella_cleridarum
            - Kurtzmaniella_fragi
            - Candida_ascalaphidarum
            - Candida_gorgasii
            - Scheffersomyces_spartinae
            - Candida_jaroonii
            - Yamadazyma_tenuis
            - Yamadazyma_philogaea
            - Yamadazyma_scolyti
            - Candida_railenensis
            - Millerozyma_acaciae
            - Millerozyma_farinosa
            - Debaryomyces_fabryi
            - Debaryomyces_hanseni
            - Debaryomyces_maramus
            - Priceomyces_carsonii
            - Priceomyces_medius
            - Priceomyces_castillae
            - Wickerhamia_fluorescens
            - Teunomyces_gatunensis
            - Teunomyces_kruisii
            - Suhomyces_pyralidae
            - Suhomyces_canberraensis
            - Kodamaea_laetipori
            - Scheffersomyces_lignosus
            - Danielozyma_ontarioensis
            - Hyphopichia_burtonii
            - Hyphopichia_homilentoma
            - Hyphopichia_gotoi
            - Meyerozyma_guilliermondii
            - Meyerozyma_spJA9
            - Meyerozyma_caribbica
            - Meyerozyma_athensensis
            - Candida_auris
            - Candida_haemuloni
            - Candida_pseudohaemulonii
            - Candida_duobushaemulonis
            - Metschnikowia_spJCM33374
            - Metschnikowia_bicuspidata
            - Metschnikowia_pulcherrima
            - Candida_intermedia
            - Clavispora_lusitaniae
            - Suhomyces_tanzawaensis
            - Scheffersomyces_stipitis
            - Candida_subhashii
            - Spathaspora_passalidarum
            - Spathaspora_spJA1
            - Candida_dubliniensis
            - Candida_tropcalis
            - Candida_maltosa
            - Candida_oxycetoniae
            - Lodderomyces_elongesporus
            - Candida_jiufengensis
            - Candida_theae
            - Candida_metapsilosis
            - Candida_parapsilosis
            - Candida_orthopsilosis
            - Candida_chilensis
        saccharomyces_cerevisiae_S288C: #CUG-Ser2, Phaffomycetaceae, Saccharomycodaceae, Saccharomycetaceae
            - Saccharomycopsis_fibuligera
            - Saccharomycopsis_malanga
            - Saccharomycopsis_fermentans
            - Saccharomycopsis_fodiens
            - Ascoidea_rubescens
            - Ascoidea_asiatica
            - Candida_ponderosae
            - Starmera_quercuum
            - Starmera_amethionina
            - Wickerhamomyces_pijperi
            - Wickerhamomyces_mucosus
            - Wickerhamomyces_ciferrii
            - Wickerhamomyces_anomalus
            - Wickerhamomyces_alni
            - Wickerhamomyces_bovis
            - Cyberlindnera_jadinii
            - Cyberlindnera_fabianii
            - Cyberlindnera_mrakii
            - Barnettozyma_californica
            - Barnettozyma_salicaria
            - Barnettozyma_pratensis
            - Candida_montana
            - Phaffomyces_opuntiae
            - Saccharomycodes_ludwigi
            - Hanseniaspora_osmophila
            - Hanseniaspora_guilliermondii
            - Hanseniaspora_opuntiae
            - Hanseniaspora_uvarum
            - Tetrapisispora_blattae
            - Vanderwaltozyma_polyspora
            - Tetrapisispora_phaffii
            - Zygosaccharomyces_mellis
            - Zygosaccharomyces_rouxii
            - Zygosaccharomyces_bailii
            - Zygosaccharomyces_parabailii
            - Zygotorulaspora_mrakii
            - Torulaspora_globosa
            - Torulaspora_spCBS2947
            - Torulaspora_delbrueckii
            - Candida_glabrata
            - Saccharomyces_paradoxus
            - Saccharomyces_pastorianus
            - Saccharomyces_eubayanus
            - Saccharomyces_boulardii
            - Naumovozyma_castellii
            - Naumovozyma_dairenensis
            - Nakaseomyces_bacillisporus
            - Kazachstania_africana
            - Kazachstania_exigua
            - Kazachstania_saulgeensis
            - Kazachstania_barnettii
            - Kazachstania_naganishii
            - Kazachstania_unispora
            - Eremothecium_sinecaudum
            - Eremothecium_cymbalariae
            - Eremothecium_gosypii
            - Ashbya_aceri
            - Kluyveromyces_marxianus
            - Kluveromyces_lactis
            - Kluyveromyces_dobzhanskii
            - Lachancea_mirantina
            - Lachancea_fermentati
            - Lachancea_quebecensis
            - Lachancea_thermotolerans
            - Lachancea_nothofagi
            - Lachancea_dasiensis
            - Lachancea_lanzerotensis
            - Lachancea_meyersii
            - Yueomyces_sinensis
            - Grigorovia_yakushimaensis
            - Grigorovia_transvaalensis


known_clades:
    Outgroups:
        - Homo_sapiens
        - Caenorhabditis_elegans
        - Crytococcus_neoformans
        - Ustilago_maydis
        - Schizosaccharomyces_pombe
        - Pneumocystis_jirovecii
        - Aspergillus_nidulans
        - Botrytis_cinerea
        - Neurospora_crassa
        - Fusarium_graminearum
    Trigonopsidaceae:
        - Trigonopsis_variabilis
        - Trigonopsis_vinaria
        - Botryozyma_nematodophila
        - Tortispora_starmeri
        - Tortispora_caseinolytica
        - Tortispora_ganteri
    Lipomycetaceae:
        - Lipomyces_starkeyi
        - Lipomyces_japonicus
        - Lipomyces_oligophaga
        - Lipomyces_doorenjongii
        - Kockiozyma_suomiensis
    Dipodascaceae:
        - Candida_hispaniensis
        - Yarrowia_bubula
        - Yarrowia_lipolytica
        - Deakozyma_indianensis
        - Wickerhamiella_sorbophila
        - Wickerhamiella_cacticola
        - Wickerhamiella_domercqiae
        - Wickerhamiella_versatilis
        - Starmerella_apicola
        - Starmerella_bombicola
        - Trichomonascus_ciferii
        - Saprochaete_ingens
        - Saprochaete_fungicola
        - Nadsonia_fulvescens
        - Nadsonia_starkeyihenricii
        - Middelhovenomyces_tepae
        - Magnusiomyces_capitatus
        - Magnusiomyces_tetraspermus
        - Dipodascus_albidus
        - Groenewaldozyma_salmanticensis
        - Zygoascus_ofunaensis
        - Zygoascus_meyerae
        - Diddensiella_caesifluorescens
        - Spencermartinsiella_europaea
        - Blastobotrys_muscicola
        - Blastobotrys_mokoenaii
        - Blastobotrys_aristatus
        - Blastobotrys_raffinosifermentans
        - Sugiyamaella_lignohabitans
        - Sugiyamaella_xylanicola
    Alloascoideaceae:
        - Alloascoidea_hylecoeti
        - Sporopachydermia_quercuum
        - Sporopachydermia_lactativora
    CUG-Ala:
        - Pachysolen_tannophilus
        - Peterozyma_xylosa
        - Nakazawaea_peltata
        - Nakazawaea_holstii
    Pichiaceae:
        - Kuraishia_capsulata
        - Kuraishia_ogatae
        - Candida_boidinii
        - Candida_arabinofermentans
        - Ogataea_parapolymorpha
        - Ogataea_polymorpha
        - Ogataea_methylovora
        - Ogataea_trehaloabstinens
        - Ogataea_kodamae
        - Ogataea_minuta
        - Ogataea_henricii
        - Ogataea_zsoltii
        - Ogataea_pilisensis
        - Ogataea_naganishii
        - Ogataea_ramenticola
        - Ambrosiozyma_maleeae
        - Ambrosiozyma_pseudovanderkliftii
        - Ambrosiozyma_philentoma
        - Ambrosiozyma_kashinagicola
        - Dekkera_bruxellensis
        - Brettanomyces_nanus
        - Brettanomyces_naardenensis
        - Kregervanrija_delftensis
        - Kregervanrija_fluxuum
        - Martiniozyma_abietophila
        - Saturnispora_silvae
        - Saturnispora_serradocipensis
        - Saturnispora_zaruensis
        - Saturnispora_mendoncae
        - Saturnispora_dispora
        - Pichia_membranifaciens
        - Candida_californica
        - Pichia_kudriavzevii
        - Pichia_terricola
        - Pichia_norvegensis
        - Pichia_nakasei
        - Pichia_exigua
        - Pichia_manshurica
        - Pichia_occidentalis
        - Candida_inconspicua
        - Komagataella_kurtzmanii
        - Komagataella_phaffii
        - Komagataella_pastoris
        - Citeromyces_siamensis
        - Citeromyces_matritensis
    CUG-Ser2:
        - Saccharomycopsis_fibuligera
        - Saccharomycopsis_malanga
        - Saccharomycopsis_fermentans
        - Saccharomycopsis_fodiens
        - Ascoidea_rubescens
        - Ascoidea_asiatica
    CUG-Ser1:
        - Babjeviella_inositovora
        - Cephaloascus_fragrans
        - Cephaloascus_albidus
        - Diutina_rugosa
        - Diutina_catenulata
        - Candida_schatavii
        - Kurtzmaniella_cleridarum
        - Kurtzmaniella_fragi
        - Candida_ascalaphidarum
        - Candida_gorgasii
        - Scheffersomyces_spartinae
        - Candida_jaroonii
        - Yamadazyma_tenuis
        - Yamadazyma_philogaea
        - Yamadazyma_scolyti
        - Candida_railenensis
        - Millerozyma_acaciae
        - Millerozyma_farinosa
        - Debaryomyces_fabryi
        - Debaryomyces_hanseni
        - Debaryomyces_maramus
        - Priceomyces_carsonii
        - Priceomyces_medius
        - Priceomyces_castillae
        - Wickerhamia_fluorescens
        - Teunomyces_gatunensis
        - Teunomyces_kruisii
        - Suhomyces_pyralidae
        - Suhomyces_canberraensis
        - Kodamaea_laetipori
        - Scheffersomyces_lignosus
        - Danielozyma_ontarioensis
        - Hyphopichia_burtonii
        - Hyphopichia_homilentoma
        - Hyphopichia_gotoi
        - Meyerozyma_guilliermondii
        - Meyerozyma_spJA9
        - Meyerozyma_caribbica
        - Meyerozyma_athensensis
        - Candida_auris
        - Candida_haemuloni
        - Candida_pseudohaemulonii
        - Candida_duobushaemulonis
        - Metschnikowia_spJCM33374
        - Metschnikowia_bicuspidata
        - Metschnikowia_pulcherrima
        - Candida_intermedia
        - Clavispora_lusitaniae
        - Suhomyces_tanzawaensis
        - Scheffersomyces_stipitis
        - Candida_subhashii
        - Spathaspora_passalidarum
        - Spathaspora_spJA1
        - Candida_dubliniensis
        - Candida_albicans
        - Candida_tropcalis
        - Candida_maltosa
        - Candida_oxycetoniae
        - Lodderomyces_elongesporus
        - Candida_jiufengensis
        - Candida_theae
        - Candida_metapsilosis
        - Candida_parapsilosis
        - Candida_orthopsilosis
        - Candida_chilensis
    Saccharomycetaceae:
        - Tetrapisispora_blattae
        - Vanderwaltozyma_polyspora
        - Tetrapisispora_phaffii
        - Zygosaccharomyces_mellis
        - Zygosaccharomyces_rouxii
        - Zygosaccharomyces_bailii
        - Zygosaccharomyces_parabailii
        - Zygotorulaspora_mrakii
        - Torulaspora_globosa
        - Torulaspora_spCBS2947
        - Torulaspora_delbrueckii
        - Candida_glabrata
        - Saccharomyces_paradoxus
        - Saccharomyces_pastorianus
        - Saccharomyces_eubayanus
        - Saccharomyces_boulardii
        - Saccharomyces_cerevisiae
        - Naumovozyma_castellii
        - Naumovozyma_dairenensis
        - Nakaseomyces_bacillisporus
        - Kazachstania_africana
        - Kazachstania_exigua
        - Kazachstania_saulgeensis
        - Kazachstania_barnettii
        - Kazachstania_naganishii
        - Kazachstania_unispora
        - Eremothecium_sinecaudum
        - Eremothecium_cymbalariae
        - Eremothecium_gosypii
        - Ashbya_aceri
        - Kluyveromyces_marxianus
        - Kluveromyces_lactis
        - Kluyveromyces_dobzhanskii
        - Lachancea_mirantina
        - Lachancea_fermentati
        - Lachancea_quebecensis
        - Lachancea_thermotolerans
        - Lachancea_nothofagi
        - Lachancea_dasiensis
        - Lachancea_lanzerotensis
        - Lachancea_meyersii
        - Yueomyces_sinensis
        - Grigorovia_yakushimaensis
        - Grigorovia_transvaalensis
    Saccharomycodaceae:
        - Saccharomycodes_ludwigi
        - Hanseniaspora_osmophila
        - Hanseniaspora_guilliermondii
        - Hanseniaspora_opuntiae
        - Hanseniaspora_uvarum
    Phaffomycetaceae:
        - Candida_ponderosae
        - Starmera_quercuum
        - Starmera_amethionina
        - Wickerhamomyces_pijperi
        - Wickerhamomyces_mucosus
        - Wickerhamomyces_ciferrii
        - Wickerhamomyces_anomalus
        - Wickerhamomyces_alni
        - Wickerhamomyces_bovis
        - Cyberlindnera_jadinii
        - Cyberlindnera_fabianii
        - Cyberlindnera_mrakii
        - Barnettozyma_californica
        - Barnettozyma_salicaria
        - Barnettozyma_pratensis
        - Candida_montana
        - Phaffomyces_opuntiae
    